server:
  port: 9091
spring:
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/,http://localhost:9091/eureka/
#    registerWithEureka: false
#    fetchRegistry: false
