server:
  port: 9090
spring:
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
    registerWithEureka: false
    fetchRegistry: false
